navapbc/labs-decision-support-tool

- infra/accounts/dev.654654379445.s3.tfbackend
- infra/app/build-repository/shared.s3.tfbackend
- infra/app/database/dev.s3.tfbackend
- infra/app/service/dev.s3.tfbackend
- infra/networks/dev.s3.tfbackend
https://navalabs.atlassian.net/browse/DST-258
> Followed steps in ticket
> DST-258: deploy infra

- app/tests/src/test_generate.py
> fix import

- app/src/ingestion/pdf_elements.py
- app/src/ingestion/pdf_postprocess.py
- app/tests/src/ingestion/test_pdf_postprocess.py
https://navalabs.atlassian.net/browse/DST-423
- Added `class Link` -- will probably need to merge with PR for https://navalabs.atlassian.net/browse/DST-414
- Added `_add_link_markdown()`
- Used `_add_link_markdown()` in `add_markdown()`
Added and updated tests.
> feat: Format links as markdown

- app/src/format.py
- app/tests/src/test_format.py
https://navalabs.atlassian.net/browse/DST-429
> add ellipses to start/middle/end of text for chunks
> feat: add ellipses to start/end of text for chunks

- README.md
https://navalabs.atlassian.net/browse/DST-487
- update docs with ingestion information and BEM example
> doc: Add data ingestion section

- app/src/app_config.py
n/a -- item from retro
- Change default from Guru SNAP (which we don't use much anymore) to CA EDD Web
Item from retro
> fix: Set CA EDD Web as default engine

- app/src/generate.py
- app/tests/mock/mock_completion.py
https://navalabs.atlassian.net/browse/DST-552
- Update system prompt
- Merging on behalf of @RyanHansz
> feat: Update prompt to include safeguards

- app/src/format.py
- app/tests/src/test_format.py
https://navalabs.atlassian.net/browse/DST-603
Have superscript citation link to source URL
https://nava.slack.com/archives/C06ETE82UHM/p1731513849101759
> fix: Have superscript citation link to source URL

- app/src/chat_engine.py
- app/src/generate.py
Discovered when working on this PR https://github.com/navapbc/labs-decision-support-tool/pull/129/files#r1844298868
Desired by Ryan, mentioned during Retro
Extract CA EDD system prompt into the chat engine
> refactor: Extract CA EDD system prompt into the chat engine

- app/src/batch_process.py
- app/src/chainlit.py
- app/tests/src/test_batch_process.py
https://navalabs.atlassian.net/browse/DST-581
- Enable lowercase input of `batch processing` command
- Add headings column and rearrange order that citations appear in
- Make column heading for citation text `citation_XX_text` instead of `citation_text`
- These small tweaks come from checking the batch generation process with a non-engineer
- Updated existing tests
> feat: Improve batch processing

- app/src/chainlit.py
- app/src/chat_engine.py
- app/src/generate.py
Associated with https://navalabs.atlassian.net/browse/DST-605
refactor: Add ChatHistory class
No behavior change
> refactor: Add ChatHistory class

- app/Makefile
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1732049333063959?thread_ts=1732047718.603639&cid=C06DP498D1D)
Add quotes around Makefile ingest arguments
> fix: Add quotes around Makefile ingest arguments

- app/src/ingest_edd_web.py
Related to #136 
Use regex to make `_fix_input_markdown()` more robust
> refactor: More robust _fix_input_markdown()

- app/src/app.py
n/a
- Allow CORS from Imagine LA's dev site
- Needed so Imagine LA test their integration non-locally
`curl -H "Origin: https://dev-social-benefits-navigator--nava-chatbot-haucptvn.web.app" -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: Content-Type" -X OPTIONS http://localhost:8000/api/query -I` passes
`curl -H "Origin: http://example.com" -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: Content-Type" -X OPTIONS http://localhost:8000/api/query -I` fails
> feat: Whitelist Imagine LA's dev site

- app/.chainlit/config.toml
- app/public/custom_script.js
- app/src/format.py
- app/tests/src/test_format.py
https://navalabs.atlassian.net/browse/DST-628
- added matching function for accordion ids to citation footnotes
- add listener for DOM changes and add onclick events to accordions through custom js file
> adding functions to python files results in an error with the frontend interpreting them as string values
1. Navigate to localhost:8000
2. Ask chatbot query
3. click on citation footnote, accordion should open
> feat: Citation footnotes open accordions

- .github/actions/configure-aws-credentials/action.yml
- .github/workflows/build-and-publish.yml
- .github/workflows/check-infra-auth.yml
- .github/workflows/ci-app.yml
- .github/workflows/ci-docs.yml
- .github/workflows/ci-infra-service.yml
- .github/workflows/ci-infra.yml
- .github/workflows/database-migrations.yml
- .github/workflows/deploy.yml
- .github/workflows/vulnerability-scans.yml
n/a
- Match action versions with latest
- This caused linting failures in my earlier PR that I missed before merging 🤦
> fix: Update checkout actions to to fix action linting

- app/src/chat_engine.py
- app/tests/src/test_chat_engine.py
- app/tests/src/test_ingest_la_county_policy.py
https://navalabs.atlassian.net/browse/DST-670
Rename dataset from "LA County Policy" to LA "DPSS Policy"
Reminder TODO once this merges: Update the `document.dataset` in the DB like [this](https://nava.slack.com/archives/C06DP498D1D/p1731639218131399?thread_ts=1731636083.093339&cid=C06DP498D1D)
Updated unit tests
> chore: Rename dataset to LA "DPSS Policy"

- app/src/app.py
https://navalabs.atlassian.net/browse/DST-722
- Updated CORS middleware configuration to use `allow_origins_regex` instead of explicit `allow_origins` list
- Added regex pattern to match all deployment URLs following the pattern: `https://dev-social-benefits-navigator--nava-chatbot-*.web.app`
Allows our backend to handle CORS for all deployment URLs based on [FastAPI CORS regex pattern best practices](https://stackoverflow.com/questions/74163301/how-to-properly-use-regex-in-cors-middleware-for-fastapi). This eliminates the need to update the origins list for each new deployment while maintaining security by only allowing requests from our specific domain pattern.
Referenced PR: [feat: Whitelist Imagine LA's dev site](https://github.com/navapbc/labs-decision-support-tool/pull/158)
Used …
> fix: Use regex pattern for CORS allowed origins

- app/gunicorn.conf.py
- app/src/batch_process.py
- app/src/chainlit.py
- app/tests/src/test_batch_process.py
- infra/app/app-config/dev.tf
Reverts the following files to their state at commit d61791c:
- app/src/batch_process.py
- app/src/chainlit.py
- app/tests/src/test_batch_process.py
- app/gunicorn.conf.py
- infra/app/app-config/dev.tf
Reverting recent batch process changes to resolve issues while preserving the commit history. PR brings back the stable version of these files from commit d61791c.
> revert: Revert batch process and related files to d61791c

- app/src/chat_engine.py
- app/src/generate.py
https://navalabs.atlassian.net/browse/DST-729
Update system prompt for ImagineLA chat engine according to https://navasage.atlassian.net/wiki/spaces/NLACBP1/pages/1570603009/Jan+2025+System+Prompt+Elements#Plain-text-updated-prompt
In chatbot web UI, compare the `System prompt` under the chatbot's settings against the desired prompt.
> Update system prompt for ImagineLA chat engine

- app/src/chat_engine.py
- app/src/ingest_runner.py
- app/src/ingestion/scrapy_dst/spiders/covered_ca_spider.py
- app/tests/src/test_chat_engine.py
https://navalabs.atlassian.net/browse/DST-683
* Add Scrapy spider for Covered CA website
* Add ingester
* Add dataset to chat engine
```
make scrapy-runner args="covered_ca --debug"
make ingest-runner args="covered_ca"
```
> feat: Add Covered CA dataset

- app/src/chat_engine.py
https://navalabs.atlassian.net/browse/DST-764
Update system prompt according to https://navasage.atlassian.net/wiki/spaces/NLACBP1/pages/1624637444/Feb+6+2025+System+prompt+updates#RTF-text-files
Check prompt in chatbot settings UI
> fix: Update system prompt

- infra/app/app-config/prod.tf
- infra/app/database/prod.s3.tfbackend
- infra/app/service/prod.s3.tfbackend
- infra/networks/prod.s3.tfbackend
- infra/project-config/networks.tf
https://navalabs.atlassian.net/browse/DST-782
- Create a prod environment -- made the Terraform edits in this PR and then ran (after authenticating into AWS):
```
make infra-configure-network NETWORK_NAME=prod
make infra-update-network NETWORK_NAME=prod
make infra-configure-database APP_NAME=prod ENVIRONMENT_NAME=prod
make infra-update-database APP_NAME=prod ENVIRONMENT_NAME=prod
make infra-configure-app-database-roles APP_NAME=app ENVIRONMENT=prod
make infra-check-app-database-roles APP_NAME=app ENVIRONMENT=prod
make infra-configure-service APP_NAME=prod ENVIRONMENT_NAME=prod
TF_CLI_ARGS_apply="-var=image_tag=85fc1a64af3ad5e32b4a1a4ba91c85d15db09b40" make infra-update-service APP_NAME=prod ENVIRONMENT_NAME=prod
```
(after grabbing the image tag from the most recent deploy)
- The …
> chore: Set up prod environment

- app/src/chat_api.py
- app/tests/src/test_chat_api.py
https://nava.slack.com/archives/C06DP498D1D/p1740606102296019
Return HTTP error upon empty `user_id`
Added unit test
> chore: API: return error on empty user_id

- app/src/chat_engine.py
https://navalabs.atlassian.net/browse/DST-808
- Match system prompt with https://navasage.atlassian.net/wiki/spaces/NLACBP1/pages/1670086694/Feb+25+2025+System+prompt+updates 
n/a
Testing canned response:
Also tested in batch mode and compared the actual with the expected answers here: https://docs.google.com/spreadsheets/d/1dIe3wo09WhA10m59HEDgv71zBuGxpFNr2KUngJ3eKqk/edit?gid=1594593032#gid=1594593032
> feat: Update prompt with new canned responses

- app/src/evaluation/metrics/logging.py
- app/src/evaluation/metrics/runner.py
- app/tests/src/evaluation/cli/test_cli_evaluate.py
- app/tests/src/evaluation/cli/test_cli_generate.py
- app/tests/src/evaluation/metrics/test_batch.py
- app/tests/src/evaluation/metrics/test_logging.py
- app/tests/src/evaluation/metrics/test_results.py
- app/tests/src/evaluation/metrics/test_runner.py
* Refactored evaluation metrics tests to use test data that is closer to what we actually can expect 
* Replaced mock objects with actual test data where possible
* using ChunkFactory, DocumentFactory, ChunkWithScore keeping in line with our existing test suite (e.g. factories.py and document.py)
Imrpoves on quality and maintainability of our evaluation metrics and CLI tests
* Modified tests passing locally `make test`, `make test-coverage`
> refactor: Fix evaluation test files with better test data using existing factory models

- app/Makefile
- app/pyproject.toml
- app/src/chainlit.py
- app/src/evaluation/literalai_exporter.py
- app/src/util/literalai_util.py
- app/tests/src/evaluation/test_literalai_exporter.py
- app/tests/src/util/test_literalai_util.py
https://navalabs.atlassian.net/browse/DST-851
feat: Add `literalai_util.py` to save LiteralAI logs for archiving
Set `LITERAL_API_KEY` env var for the prod or dev env
```
make literalai-archiver args="--help"
make literalai-archiver args="2025-03-06 2025-03-10"
```
> feat: Add utility to save LiteralAI logs for archiving

- app/src/evaluation/literalai_exporter.py
- app/tests/src/evaluation/test_literalai_exporter.py
https://navalabs.atlassian.net/browse/DST-885
- Make CSV format follow a defined order with formatted column headings and some minor formatting of e.g., the Date column
- Requested by design to minimize effort exporting changes
- Test locally with the LiteralAPI key or see the unit test coverage
- Service endpoint: https://p-278-app-dev-939749599.us-east-1.elb.amazonaws.com
- Deployed commit: cb989f87a4894e2002f1e3e2daaffa5b39fe5e5d
> chore: Rename and reorder columns in LiteralAI export

- app/src/evaluation/literalai_exporter.py
n/a
- Remove header function and get headings from first row
- Follow up to https://github.com/navapbc/labs-decision-support-tool/pull/278 with suggested changes from reviewer
Existing unit test
- Service endpoint: https://p-279-app-dev-616002210.us-east-1.elb.amazonaws.com
- Deployed commit: 1f0ff2af9bb210008fec712815c4a1b8526d7a61
> refactor: Get header from first QA row

- app/src/chainlit_data.py
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1742934060676919?thread_ts=1742914226.216779&cid=C06DP498D1D)
Add DB connection pool for Chainlit data layer 
After deployment, ensure DB connections continue to work after 15 minutes.
- Service endpoint: https://p-280-app-dev-299654791.us-east-1.elb.amazonaws.com
- Deployed commit: ca053e2e85af9bcdfabc8e0ff88b2112798cf23b
> feat: Add DB connection pool for Chainlit data layer

- app/src/chat_engine.py
https://navalabs.atlassian.net/browse/DST-903
System prompt 1
- Edit referral link sentence format. 
- Added more referral links
System prompt 2
- Moved non-styling reference info to a new section. 
- Added more guidance for answering questions about benefits based on immigration status. Added guidance for a few more topics.
https://navasage.atlassian.net/wiki/spaces/NLACBP1/pages/1753776129/Mar+28+2025+System+prompt+updates
None
- Service endpoint: https://p-287-app-dev-1197781843.us-east-1.elb.amazonaws.com
- Deployed commit: 88778a586102f42033de78b5e6e8251111e7d44d
> chore: Update system prompts based on pilot user usage

- app/src/chainlit.py
- app/src/chat_api.py
- app/src/citations.py
- app/src/format.py
- app/src/generate.py
- app/tests/src/test_chat_api.py
- app/tests/src/test_citations.py
- app/tests/src/test_format.py
https://navalabs.atlassian.net/browse/DST-918
* remove unknown citation ids
Upon further investigation, the following fixes were also made
* Set the `raw_response` metadata to the response resulting from `simplify_citation_numbers()`. The `raw_response` metadata is used to rebuild the chat history in Chainlit.
* For Chainlit, add a newline before _every_ list, not just the first list.
Follow error replication instructions in ticket.
Also check for any markdown to html formatting errors, especially for lists, which Claude creates more of compared to OpenAI.
- Service endpoint: https://p-291-app-dev-920550937.us-east-1.elb.amazonaws.com
- Deployed commit: 81c74171040cd4f62bd6cd2bf99c48f5156daa01
> fix: Ignore unknown citations and other related fixes

- app/src/evaluation/literalai_exporter.py
- app/src/util/literalai_util.py
- app/tests/src/evaluation/test_literalai_exporter.py
https://navalabs.atlassian.net/browse/DST-905
Added 2 new columns: `Feedback Scores` and `Feedback Comments`
[Slack](https://nava.slack.com/archives/C06ETE82UHM/p1745337881857479?thread_ts=1745336407.256119&cid=C06ETE82UHM)
- Service endpoint: https://p-295-app-dev-1161573805.us-east-1.elb.amazonaws.com
- Deployed commit: d1328415c550346f02dab274700a39512cee97cf
> feat: Include feedback scores and comments in LiteralAI export

- README.md
- docs/releases.md
n/a
- Document our release and deployment strategy.
- Service endpoint: https://p-297-app-dev-90124877.us-east-1.elb.amazonaws.com
- Deployed commit: b9d3036084ceb846951c103f381bfa52a6c25074
> docs: Add details on production deployments

- app/src/chat_engine.py
https://navalabs.atlassian.net/browse/DST-1034
Tweak system prompt 2 to  "include a reference to the Benefit Info Hub to reinforce for users what topics are in scope"
See https://navalabs.atlassian.net/browse/DST-1034?focusedCommentId=12680
- Service endpoint: https://p-320-app-dev-1904595690.us-east-1.elb.amazonaws.com
- Deployed commit: 514a3d458e697f8f36bf00db910c57aa89406123
> fix: Improve response for out-of-scope questions

- infra/app/app-config/env-config/monitoring.tf
https://navalabs.atlassian.net/browse/DST-1011
Remove the Nava Labs alerts email address
TODO:
`make infra-update-app-service APP_NAME=app ENVIRONMENT=prod`
None
- Service endpoint: https://p-323-app-dev-734484649.us-east-1.elb.amazonaws.com
- Deployed commit: 642c5df4aff4ce6355c519a99865f3072298fe4b
> chore: Remove email alerts for app response time
