- app/src/chainlit.py
- app/src/generate.py
- app/src/retrieve.py
- app/tests/mock/mock_completion.py
- app/tests/mock/mock_sentence_transformer.py
- app/tests/mock/test_mock_sentence_transformer.py
- app/tests/src/db/models/factories.py
- app/tests/src/test_generate.py
- app/tests/src/test_retrieve.py
https://navalabs.atlassian.net/browse/DST-272
- Add retrieve() and test coverage
- Add context keyword to generate() and test coverage
- Integrate these into chainlit.py
- Simplify the math behind the MockSentenceTransformer, and fix a bug in the ChunkFactory
Spin up the app at localhost:8000/chat, then run `make logs` (after you've ingested Guru cards) and ask a question. The logs should show the queried cards:
> feat: Augment response with retrieved cards

- app/.chainlit/config.toml
- app/.chainlit/translations/en-US.json
- app/.gitignore
- app/src/chainlit.py
- app/src/format.py
- app/src/generate.py
- app/src/retrieve.py
- app/tests/src/test_format.py
- app/tests/src/test_retrieve.py
https://navalabs.atlassian.net/browse/DST-282
- Commit the `.chainlit` folder (this is the majority of the additions in this PR)
- Enable the unsafe_html in the config, and set custom HTML and JS for accordions from USWDS. Also enable light mode and disable file uploads
- Add a `format_guru_cards` function and append the output to the response of the user message
- Refactor `retrieve` into two functions, `retrieve` and `retrieve_with_scores`. The initial implementation was `retrieve_with_scores`, but we don't use it yet, so this simplifies the code. Also moved logging out of chainlit.py and directly into these functions. Add test coverage for these.
Tests added for formatter, manual testing screenshot below:
> feat: Show accordions with cards

- infra/modules/database/main.tf
https://navalabs.atlassian.net/browse/DST-298
- Move auto scaling for DB from 2-4 to .5-1
- We don't expect many simultaneous users, and only a relatively small amount of data in the DB, so don't need heavy scaling. I initially set it this way to be confident the application would run, but manual testing suggests it works fine at these lower levels for our current level of usage.
> perf: Lower database auto-scaling settings

- app/src/chainlit.py
- app/src/chat_engine.py
- app/src/util/class_utils.py
- app/tests/src/test_chat_engine.py
https://navalabs.atlassian.net/browse/DST-327
- Add `ChatEngineInterface` abstract class that acts as an interface for chat engines
- Refactor existing chatbot backend to `GuruMultiprogramEngine` class
- Add placeholder engines: `GuruSnapEngine` and `PolicyMichiganEngine`
* Go to `chat/` or `/chat/?engine=unknownEngine`, expect "Available engines: ['guru-snap', 'policy-mi', 'guru-multiprogram']"
* Go to `/chat/?engine=guru-multiprogram`, expect "Chat engine started: Guru Multi-program Chat Engine"
- Expect normal behavior after submitting a question
* Go to `/chat/?engine=guru-snap`, expect "Chat engine started: Guru SNAP Chat Engine"
- Expect "TEMP: Replace with generated response once chunks are correct"
* Go to `/chat/?engine=policy-mi`, expect "Chat engine started: Michigan Bridges …
> feat: Use URL query 'engine' parameter to set chatbot's configuration

- app/gunicorn.conf.py
- docker-compose.yml
> change amount of worker #'s to 1
> Chainlit uses Socket.io for backend server connections; multiple workeres are currently unsupported by gunicorn
https://flask-socketio.readthedocs.io/en/latest/deployment.html#gunicorn-web-server
> Run `make start`
> Navigate to `localhost:8000/chat` and enter a query into the chatbot, response should be returned
> fix: set uvicorn worker to 1

- app/gunicorn.conf.py
- app/src/app_config.py
- app/src/chainlit.py
As requested by Ryan, set the default chat engine to 'guru-snap'.
Change default chat engine to 'guru-snap'.
Navigate to `/chat` (without the `engine` query parameter), expect "Chat engine started: Guru SNAP Chat Engine".
Navigate to `/chat/?engine=someNonExistingEngineId` to see available engines.
> feat: Set default chat engine to 'guru-snap'

- app/src/chat_engine.py
- app/src/retrieve.py
- app/tests/src/db/models/factories.py
- app/tests/src/test_retrieve.py
https://navalabs.atlassian.net/browse/DST-328
follow-on to PR #27
Flush out the `GuruSnapEngine` implementation by enabling query the DB using filters (SQL `WHERE`) against the new `dataset`, `program`, and `region` columns.
Grab datasets from [our S3 bucket](https://us-east-1.console.aws.amazon.com/s3/buckets/decision-support-tool-app-dev?bucketType=general&region=us-east-1&tab=objects#), and move them to the `app` folder. ([dataset descriptions](https://nava.slack.com/archives/C06ETE82UHM/p1717787155567219?thread_ts=1717783522.574479&cid=C06ETE82UHM))
```
make db-recreate
make ingest-guru-cards DATASET_ID=guru-snap BENEFIT_PROGRAM=SNAP BENEFIT_REGION=Michigan FILEPATH=/app/guru_cards_setA.json
make ingest-guru-cards DATASET_ID=guru-multiprogram BENEFIT_PROGRAM=multiprogram …
```
> feat: Retrieve from database based on filters

- app/src/chainlit.py
- app/src/chat_engine.py
- app/src/db/models/document.py
- app/src/format.py
- app/src/generate.py
- app/src/retrieve.py
- app/tests/src/test_format.py
- app/tests/src/test_generate.py
- app/tests/src/test_retrieve.py
Follow-on PR to address https://github.com/navapbc/labs-decision-support-tool/pull/30#discussion_r1685514610
Refactor code to use generalized `ChunkWithScore` class to minimize exposure of `sqlalchemy` into other code unnecessarily and reduce coupling of that code to a DB.
No code behavior change.
> refactor: Use generalized ChunkWithScore

- app/gunicorn.conf.py
- app/src/app_config.py
- app/src/chainlit.py
- app/src/chat_engine.py
- app/src/ingest_guru_cards.py
- app/src/login.py
- app/src/retrieve.py
- app/src/shared.py
- app/tests/conftest.py
- app/tests/src/test_format.py
- app/tests/src/test_ingest_guru_cards.py
- app/tests/src/test_login.py
- app/tests/src/test_retrieve.py
From [Slack](https://nava.slack.com/archives/C06DP498D1D/p1721764756834649):
> - [retrieve_with_scores()](https://github.com/navapbc/labs-decision-support-tool/blob/cb9d663d1f575cc06119f561893eff3ee099288e/app/src/retrieve.py#L15) and [_ingest_cards()](https://github.com/navapbc/labs-decision-support-tool/blob/cb9d663d1f575cc06119f561893eff3ee099288e/app/src/ingest_guru_cards.py#L26) take the 2 arguments `db_session` and `embedding_model`.
> - I see these 2 arguments as "[context](https://www.baeldung.com/cs/context-design-pattern)" or "fixtures", and not really arguments that would change with different calls to these functions.
> - Additionally, any retrieval function should use the same `embedding_model` as the ingest function.
> What do y'all think about wrapping these 2 arguments …
> refactor: Move db_session and embedding_model args into AppConfig

- app/tests/conftest.py
- app/tests/src/test_format.py
- [removed unnecessary MockAppConfig](https://github.com/navapbc/labs-decision-support-tool/commit/e039d51ccb9685eb9a21d9c1ce29a7dcc39c249a)
- [removed unused monkeypatch parameter](https://github.com/navapbc/labs-decision-support-tool/commit/43ac5f5497d18e4f0ee4112e2da4aa7778046963)
No code behavior changes
> refactor: Remove extraneous MockAppConfig and monkeypatch parameter in tests

- app/local.env
- app/src/app_config.py
- app/src/retrieve.py
- app/src/util/embedding_models.py
- app/tests/mock/test_mock_sentence_transformer.py
- app/tests/src/test_retrieve.py
- docs/app/getting-started.md
https://navalabs.atlassian.net/browse/DST-352
Currently scores are not normalized, so their range is unknown. It is common to normalize the scores so that they range from -1 to 1.
Normalize similarity scores of retrieved Guru cards by using the `multi-qa-mpnet-base-cos-v1` embedding model, which normalizes the vector saved to the DB.
Also added manual test and confirmed that the `max_inner_product` method returns the same score magnitude as using `sentence_transformers.util.dot_score` used in code at https://huggingface.co/sentence-transformers/multi-qa-mpnet-base-cos-v1.
Scores from the DB query are negated, presumably to reverse the default sort order, so the code reverses the negation when recording the score in `ChunkWithScore`; also updated associated test.
```
make db-recreate
make …
```
> feat: Normalize similarity scores of retrieved Guru cards

- app/src/app_config.py
- app/src/chainlit.py
- app/src/chat_engine.py
- app/src/format.py
- app/src/retrieve.py
- app/tests/conftest.py
- app/tests/src/test_chat_engine.py
- app/tests/src/test_format.py
- app/tests/src/test_retrieve.py
https://navalabs.atlassian.net/browse/DST-356
Currently, the chatbot has 1 threshold (retrieval-k) that controls both:
- retrieval-k: the number of retrieved docs (e.g., Guru cards) that gets sent to the LLM for it to generate the free-text response, and
- the retrieved docs that gets shown to the user (which I’ll call max-num-docs-shown)
We want to be able to control these 2 thresholds independently because:
- we may want to have a high retrieval-k to give as much context as possible to the LLM
- but limit max-num-docs-shown to the user
We also want to control the docs shown based on the retrieval/similarity/relevance score, so also add a docs-shown-min-score, which will also limit the number of docs shown, i.e., a doc will only be shown if it meets the docs-shown-min-score AND does not …
> feat: Add retrieval and docs_shown thresholds

- app/src/ingest_guru_cards.py
- app/src/ingest_policy_pdfs.py
- app/src/util/ingest_utils.py
- app/tests/src/test_ingest_guru_cards.py
- app/tests/src/test_ingest_policy_pdfs.py
n/a
- Pass the DB session as a parameter to the ingest functions
- The wrapper function in ingest utils controls the commit, so the ingestion function for Guru Cards need to use the same session, otherwise the session it uses never commits
> fix: Commit after ingesting Guru cards

- app/src/format.py
- app/tests/src/test_format.py
https://navalabs.atlassian.net/browse/DST-374 
> extract accordion format html to function
> change _get_bem_docs_to_show
- run `make start` in app directory
- navigate to http://localhost:8000/chat/?engine=bridges-eligibility-manual
- set `Minimum document score required for generating LLM response` and `Minimum document score required to show document in the UI` to -1
- run query
> feat: add accordion chunk citations

- app/src/chainlit.py
- app/src/chat_engine.py
- app/src/format.py
- app/tests/src/test_format.py
https://nava.slack.com/archives/C06DP498D1D/p1723490546680209
- Rename `docs_shown_*` variable to `chunks_shown_*` to avoid confusion with `Document` DB entities
- Update their description in the UI
No behavior change.
> fix: Rename docs_shown_* variable to chunks_shown_*

- app/src/chainlit.py
- app/tests/conftest.py
- app/tests/src/test_chainlit.py
- app/tests/src/test_format.py
- app/tests/src/test_generate.py
https://navalabs.atlassian.net/browse/DST-373
- Log each retrieved chunk's document name, ID, and similarity score to the query in the metadata for Chainlit
- n/a
Removing the cast to str for settings is safe:
Metadata in LiteralAI dashboard:
> feature: Log metadata for retrieved chunks

- app/src/chainlit.py
- app/src/format.py
- app/tests/src/test_chainlit.py
- app/tests/src/test_format.py
https://navalabs.atlassian.net/browse/DST-399 
> added internal citation to inside of loop to avoid dups
> adjusted substitution code for line breaks 
Navigate to http://localhost:8000/chat/?engine=bridges-eligibility-manual
Adjust min citation params to -1
Queries to test
- This client's grandmother just moved in, how do they add them to the case?
- Client lives with a roommate, can they get SNAP separately?
> bug: citation duplicates and accordion overflow

- app/src/format.py
- app/tests/src/test_format.py
https://navalabs.atlassian.net/browse/DST-375
- Link accordion titles to BEM document
- Link references in chunk text
- I'm a little torn on how to handle the case of no matching BEM ### in `_get_bem_url` -- raising an exception felt a bit cleaner, but an alternative would be to return `str | None`.
> feat: Link to BEM documents

- app/src/ingestion/get_grouped_texts.py
- app/tests/src/ingestion/test_get_grouped_texts.py
Merge list items only if they have the same heading, instead of logging a warning when they have different headings.
Updated test_concatenate_list_items() to include LIST_ITEM in new heading that should not be merged.
> fix: Merge list items only if they have the same heading

- app/src/ingestion/pdf_stylings.py
- app/src/util/pdf_tag_extractor.py
- app/tests/src/ingestion/test_pdf_stylings.py
https://navalabs.atlassian.net/browse/DST-413
Added `app/src/ingestion/pdf_stylings.py` to provide `extract_stylings()` function that returns a list of Styling reflecting bolded text that is not a heading and not in the header or footer. For example:
```python
Styling(
text="CDC not eligible due to 6 month penalty period",
pageno=3,
headings=[Heading(title="Disqualifications", level=1, pageno=2)],
wider_text="• First occurrence - six month disqualification. The "
"closure reason will be CDC not eligible due to 6 month "
"penalty period. ",
bold=True,
)
```
for
Added `test_pdf_stylings.py`
> feat: Utility to extract bolded text from PDFs

- app/src/ingestion/pdf_elements.py
- app/src/ingestion/pdf_postprocess.py
- app/tests/src/ingestion/test_pdf_postprocess.py
https://navalabs.atlassian.net/browse/DST-425
Added `_should_merge_text()` that merges texts (`NarrativeText` or `List`) that are split across consecutive pages
Updated test for `group_texts()`
> feat: Merges texts that are split across consecutive pages

- app/tests/src/test_ingest_bem_pdfs.py
https://nava.slack.com/archives/C06DP498D1D/p1725380936499099?thread_ts=1725375586.922079&cid=C06DP498D1D
The cropped 100.pdf used for testing stripped the outline metadata, which is why I [use a new complete file](https://github.com/navapbc/labs-decision-support-tool/blob/903bab7acb82f7d54b2aac696dcedcdbb053bf8f/app/tests/src/util/test_pdf_utils.py#L23) when testing anything that uses the PDF outline.
Use 707.pdf to test ingest_bem_pdfs.py
> test: Use 707.pdf to test ingest_bem_pdfs.py

- app/Dockerfile
- app/src/ingest_bem_pdfs.py
- app/src/ingestion/pdf_elements.py
- app/src/ingestion/pdf_postprocess.py
- app/src/ingestion/pdf_stylings.py
- app/tests/src/ingestion/test_pdf_postprocess.py
- app/tests/src/test_ingest_bem_pdfs.py
- [Heuristic 1](https://nava.slack.com/archives/C06DP498D1D/p1725396917417349?thread_ts=1725395128.529479&cid=C06DP498D1D): if a `ListItem` or `List` ends with a bullet, merge with the next element.
- [add more assertions to check text and headings](https://github.com/navapbc/labs-decision-support-tool/commit/8935ba12952994324a311c78cfdf862e227295e9)
- heuristic 1: [merge text ending with bullet with next element](https://github.com/navapbc/labs-decision-support-tool/pull/71/commits/121181c792e9d54cd7fa631ede3d05cf9b32c8f0)
- fix: [unstructured will strip() texts, so we need to strip the styling text as well](https://github.com/navapbc/labs-decision-support-tool/pull/71/commits/7a4897f96d8da29332b07c6dc25c1fc09c334771)
- [fix processing Title elements to not cause …
> fix: Add heuristics and fixes to improve BEM pdf parsing

- app/src/chat_engine.py
- app/src/citations.py
- app/src/format.py
- app/src/generate.py
- app/tests/src/test_citations.py
- app/tests/src/test_format.py
https://navalabs.atlassian.net/browse/DST-435
- Slightly update LLM prompt:
- to encourage `(chunk-0)(chunk-1)` style citations (which our code supports) rather than `(chunk-0,1)` (which the LLM invents)
- to encourage adding citations after punctuation.
- Remove similarity scores from UI
- Set defaults for BEM engine similarity score cut off to -1, and match citations shown k with retrieval k (8)
- Update citations UX to match the Figma prototype (see ticket for screenshot)
- Add hotfix for proper markdown list rendering by Chainlit
n/a
> feat: Update citation UI

- app/src/ingest_bem_pdfs.py
- app/src/ingestion/pdf_postprocess.py
- app/src/util/string_utils.py
- app/tests/src/ingestion/test_pdf_postprocess.py
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1726761922331469)
PR #79 resulted in bigger chunks and more use of `split_paragraph()` and `split_list()`, which revealed some outlier error cases.
- Account for higher token counts per chunk when text is split by adding a 20% fudge factor
- Always merge LIST_ITEMs with the prior text, regardless if it doesn't end with `:`
- Account for lists with no introductory sentence
- Correctly split parsed tables, which are not grouped into a single paragraph
Ingest all the BEM pdfs and check chunks
> fix: Address BEM PDF ingestion error cases with bigger chunks

- app/src/chainlit.py
- app/src/chat_engine.py
- app/src/format.py
n/a
- Add an h3 element between the LLM response and the citations HTML
- Unrelated change: increase the UI slider max for retrieved citations
- Without a heading, if the LLM response ends in list items, Chainlit will render the following HTML as another list bullet.
Example bug:
After fixing:
> fix: Prevent citations from being rendered inline by Chainlit

- .github/workflows/ci-app.yml
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1727795570823389)
Set test coverage thresholds.
The PR check will fail if thresholds aren't met.
Tested here: https://github.com/navapbc/labs-decision-support-tool/pull/83#issuecomment-2386124218
which now shows a red status.
> fix ci: Set test coverage thresholds

- bin/deploy-release
n/a
Ports over this PR: https://github.com/navapbc/template-infra/pull/761
TL;DR - our service takes about ~11 minutes to become stable, but the AWS command won't wait for longer than 10 minutes, so we run it a second time if the first one fails.
See linked PR above
> fix: Retry waiting for service to be stable

- app/Dockerfile
- docs/decisions/infra/0007-database-migration-architecture.md
PR checks are [failing](https://github.com/navapbc/labs-decision-support-tool/actions/runs/11237920089/job/31241445501?pr=89#step:3:2670) due to:
```
The specified Python version (3.13.0) is not supported by the project (>=3.12,<3.13).
Please choose a compatible version or loosen the python constraint specified in the pyproject.toml file.
```
I was able to replicate locally via make build.
What's causing the problem? What changed?
Hypothesis: The [Docker container image](https://hub.docker.com/_/python/tags?name=3-slim) was updated to Python 3.13 overnight.
Pin Python version to `python:3.12-slim` for Docker image.
PR checks should pass.
> ci: Use python:3.12-slim for Docker image

- app/src/app_config.py
- app/src/generate.py
- app/tests/mock/mock_completion.py
n/a -- quick change from our conversation during team time yesterday
Set temperature to 0.0 for more repeatability
Tricky to test because OpenAI doesn't actually respect temperatures of 0 (it will still be somewhat non-deterministic). I ran the same question through multiple times and did observe more consistent responses with the setting explicitly at 0.
Zero -- note the "key points" phrasing is consistent:
Non-zero, either set explicitly to 1 or omitted from the API call:
> feat: Make temperature configurable and set default to 0.0

- app/src/ingestion/edd/spiders/edd_spider.py
- app/src/util/string_utils.py
- app/tests/src/util/test_string_utils.py
https://navalabs.atlassian.net/browse/DST-536
Added regex to replace incomplete URLs with absolute URLs.
Scrapy does not appear to have a built-in feature for this based on:
- https://github.com/scrapy/scrapy/issues/548
Tried to update the `href` attributes on `<a>` HTML tags, but I couldn't update the `response` object besides `.drop()`.
Run `DEBUG_SCRAPINGS=true poetry run scrape-edd-web`
Search for relative links (i.e., text with `](/` or `]([a-g,i-z]` etc):
```
grep '](/' src/ingestion/pretty-edd_scrapings.json
grep ']([a-g,i-z]' src/ingestion/pretty-edd_scrapings.json
ggrep -P '\]\((?!http)' src/ingestion/pretty-edd_scrapings.json
```
> fix: Resolve incomplete URLs

- app/src/ingestion/edd/spiders/edd_spider.py
Exclude news-related webpages when scraping the edd.ca.gov website
None.
> fix: Exclude EDD news-related webpages

- app/src/ingestion/edd/spiders/edd_spider.py
Expanding on #100, exclude webpages related to WSINs (Workforce Services Information Notices)
- exclude WSIN (Workforce Services Information Notice) webpages
- Use regex to exclude more irrelevant webpages
`DEBUG_SCRAPINGS=true poetry run scrape-edd-web`
Reduces webpages to scrap to about 800 pages
> fix: Exclude WSIN webpages

- app/src/citations.py
- app/tests/src/test_citations.py
https://navalabs.atlassian.net/browse/DST-510
Rejoin headings with the subsequent first paragraph so that headings are not cited by themselves.
Updated unit test
> fix: Rejoin headings with the subsequent first paragraph

- app/src/format.py
n/a
Render `{citation_headings}`  to avoid an empty line, which causes Chainlit to render what follows as markdown instead of HTML.
Without change:
With change:
> fix: Render citation headings HTML on same line as div

- app/src/ingestion/edd/spiders/edd_spider.py
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1729707559404419)
Ignore all EDD page ending in `social-media-toolkit`. They have complex tables; we'll address them later if needed.
```
DEBUG_SCRAPINGS=true poetry run scrape-edd-web
make ingest-edd-web DATASET_ID=ca-edd-web BENEFIT_PROGRAM=employment BENEFIT_REGION=California FILEPATH=src/ingestion/edd_scrapings.json
```
> fix: Ignore all EDD social-media-toolkit webpages

- infra/app/app-config/dev.tf
n/a
- Update default CPU and memory for ECS tasks such as data ingestion run in the `dev` environment
- The web ingestion task runs out of memory with the default of 4GB.
> perf: Increase CPU and memory of ECS tasks

- app/src/format.py
- app/tests/src/test_format.py
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1729789701680649?thread_ts=1729780302.454019&cid=C06DP498D1D)
When the EDD webpage skips from H1 to H3 without any H2 heading, the breadcrumb shows 2 consecutive arrows:
Don't show 2 consecutive arrows when a heading is missing. Instead, show a single arrow between headings.
Added unit test
> fix: Citations UI: Show single arrow for missing middle headings

- app/.gitignore
- app/src/format.py
- app/tests/src/test_format.py
n/a
- Show only the deepest two headers
- If the top of the two deepest is the same as the document name, skip it
- Unrelated change: gitignore Chainlit translation files (not sure what process is generating these)
From quick Slack conversation with design: https://nava.slack.com/archives/C06ETE82UHM/p1729864998665799
> fix: Show only two nested headers

- app/src/chainlit.py
- app/tests/src/test_chainlit.py
https://navalabs.atlassian.net/browse/DST-560
- add raw response (instead of HTML-formatted response) to metadata and pull from context
add print statement to line 81, message output should be list of exchanges indicated by `role` and `content`
> perf: Use raw responses of chat context in chat history

- app/src/batch_process.py
- app/tests/src/test_batch_process.py
n/a
- Instead of gathering the keys from the first processed row of the CSV, gather all of the keys from all of the rows (since later rows may have more keys if they have more citations)
Added coverage to the test for this function. The test will now fail if the change is reverted
> fix: Include all headers in batch CSV generation

- README.md
- app/src/chat_engine.py
- app/src/format.py
https://navalabs.atlassian.net/browse/DST-534
* Show `document.dataset` in the UI citations
* Updated README.md
Re-ingest with the correct `DATASET_ID` (30 mins):
```
cd app
DEBUG_SCRAPINGS=true poetry run scrape-edd-web
touch SAVE_CHUNKS
make ingest-edd-web DATASET_ID="CA EDD" BENEFIT_PROGRAM=employment BENEFIT_REGION=California FILEPATH=src/ingestion/edd_scrapings.json
```
or update your DB (1 second):
`update "document" set dataset='CA EDD' where dataset ='ca-edd-web'`
After [fix citation_subsection.text conversion to html](https://github.com/navapbc/labs-decision-support-tool/pull/125/commits/ef6e3979283c453e42903a7bf810af1ed38671d6):
> feat: Show document.dataset in UI; fix: citation markdown rendering

- app/src/chainlit.py
- app/src/chat_engine.py
- app/src/format.py
- app/tests/src/test_format.py
Related to #128
Refactor to use `FormattingConfig` and `BemFormattingConfig` instead of `if-then` blocks.
> refactor: Use FormattingConfig in format.py

- app/src/ingest_edd_web.py
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1732056132833719?thread_ts=1732047718.603639&cid=C06DP498D1D)
fix: Handle blank sublist for EDD ingest of https://edd.ca.gov/en/unemployment/Employer_Information/
> fix: Handle blank sublist for EDD ingest

- app/src/chainlit.py
- app/src/generate.py
- app/tests/src/test_chainlit.py
- app/tests/src/test_generate.py
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1732130712387439)
* Move `chat_history.pop()` to `chainlit.py`
* Exclude `system` messages from the return value of `extract_raw_chat_history()` since we provide `system` messages in `generate()`.
No behavior change
> refactor: Exclude user's latest message from chat_history

- app/src/app_config.py
- app/src/chat_api.py
- app/src/chat_engine.py
- app/tests/src/test_chat_api.py
https://navalabs.atlassian.net/browse/DST-586
- Add new chat engine that pulls from both Imagine LA and EDD web datasets
- Set as the default both for web and API interfaces
- This will be the engine we use for the pilot going forward
- I'll seek input from design on how we can update the prompt here, I edited it to be generic to CA (rather than EDD specific) for now
> feat: Add Imagine LA engine

- app/notebooks/question_answer_generator/generate_q_a_pairs.py
- app/notebooks/question_answer_generator/q_a_generation.ipynb
https://navalabs.atlassian.net/browse/DST-588
> Updated notebook with following
> add dataset key with multiselect widget
> change chunk/document selection to radio widget
```
Run make notebook
navigate to http://localhost:8888/
copy and paste token in URL found in terminal
run notebook file in notebooks/question_answer_generator/q_a_generation.ipynb
question_answer_pairs.csv should be created with question, answer, document_name, document_source, dataset, document_id, and chunk_id fields
```
> feat: add question generation for imagine la and bem dataset 

- app/src/util/ingest_utils.py
Related to https://navalabs.atlassian.net/browse/DST-564
Remove use of `getopt` for ingestion since we're not using any [getopt options](https://docs.python.org/3/library/getopt.html) -- we're using "arguments" only.
No behavior change. 
Run some ingestion command.
> fix: Remove use of getopt for ingestion

- app/src/ingestion/imagine_la/scrape/scrape_content_hub.py
Handle the case where the `root_url` argument ends with `"/"`
Before this PR, running `python scrape_content_hub.py https://socialbenefitsnavigator25.web.app/contenthub/ ...` would strip the first character of the `page_path` such that `calworks.html` would instead be saved as `alworks.html`.
Running with this PR, scraping should save the correct filenames, which are used to set `document.source`.
> fix: ImagineLA scraper: handle '/' suffix for root_url 

- app/src/citations.py
- app/tests/src/test_citations.py
[Slack](https://nava.slack.com/archives/C06ETE82UHM/p1733771384506999?thread_ts=1733771029.694449&cid=C06ETE82UHM)
- Ignore dashes (for table markdown text) as well as spaces when checking if subsection text is in the chunk text.
- Also downgrade to a `log.warning` (rather than `assert`) since this check occurs during user interaction
Added unit test
> fix: Handle table markdown formatting in assertion

- .github/workflows/build-and-publish.yml
- .github/workflows/check-infra-auth.yml
n/a
- Install Terraform on action host
- Two actions call the AWS credentials action which relies on Terraform, but the latest version of Ubuntu does not include Terraform by default
> fix: Setup Terraform before AWS credentials

- app/src/app_config.py
- app/src/chat_api.py
- infra/app/app-config/env-config/environment-variables.tf
https://navalabs.atlassian.net/browse/DST-666
- Set up new project in Literal
- Add new secret to AWS Parameter Store, `LITERAL_API_KEY_FOR_API`
- If this env variable is set, use it for the Literal client used by the API
- This better isolates usage of the API in preparation for a pilot
Setting the variable locally, a query via the API appears in the Literal dashboard:
Here is the variable set in the AWS parameter store:
> feat: Use separate Literal project for API

- app/src/batch_process.py
- app/src/chainlit.py
- app/tests/src/test_batch_process.py
https://navalabs.atlassian.net/browse/DST-709
- Updated message formatting in `chainlit.py` to ensure completion status is visible in UI
- Added proper metadata tracking for processing status
- Made completion message more descriptive by including result filename
The batch processing feature was not showing completion messages in the UI, even though they were being logged successfully. Investigation showed that messages with author "backend" were not consistently visible in the Chainlit UI.
Key changes:
- Added metadata to include processing status and file information
- Made completion message more informative by including the output filename
- Ensured consistent message visibility throughout the processing flow
This PR is part of improving the batch processing feature's user experience, …
> fix: Ensure UI feedback message for batch processing completion

- app/src/batch_process.py
- app/src/chainlit.py
- app/tests/src/test_batch_process.py
https://navalabs.atlassian.net/browse/DST-688
- Modified `batch_process.py` to use sequential processing instead of parallel processing
- Added explanatory comments about the thread-safety concerns with LiteLLM
This PR addresses the Docker deployment crashes (CPU >1400%) issue when processing CSVs with multiple rows. Investigation revealed that the high CPU usage was caused by thread-safety issues in the underlying LiteLLM client libraries when running in parallel.
The fix is simple but effective: we've removed the parallel processing implementation and switched to sequential processing. This change resolves the CPU spike issues we were seeing in Docker deployments.
1. UI feedback issue: "File processed, results attached" message appears in logs but not in UI
2. Assessment needed: …
> fix: Switch to sequential processing in batch_process to resolve thread-safety issues

- README.md
- app/.gitignore
- app/Makefile
- app/src/ingest_edd_web.py
- app/src/ingest_la_county_policy.py
- app/src/ingestion/imagine_la/ingest.py
- app/src/ingestion/scrape_la_policy.py
- app/src/ingestion/scrapy_runner.py
- app/src/util/ingest_utils.py
- app/tests/src/ingestion/imagine-la/test_ingest.py
- app/tests/src/test_ingest_edd_web.py
- app/tests/src/test_ingest_la_county_policy.py
- app/tests/src/test_ingest_utils.py
https://navalabs.atlassian.net/browse/DST-669
For the 3 datasets (EDD, Imagine LA's Information Hub, LA County ePolicy manual):
* Write markdown files for each document content
* Write split/chunk files for each document
If you don't have src/ingestion/edd_scrapings.json, refer to testing description in PR #121 or do the following:
``` 
cd app
make scrape-edd-web
```
Then create md files under folder `edd_md`:
```
make ingest-edd-web DATASET_ID="CA EDD test" BENEFIT_PROGRAM=employment BENEFIT_REGION=California FILEPATH=src/ingestion/edd_scrapings.json INGEST_ARGS="--skip_db"
```
If you don't have src/ingestion/la_policy_scrapings.json, refer to testing description in PR #161 or do the following:
```
make scrape-la-county-policy
```
Then create md files under folder `la_policy_md`:
``` …
```
> feat: Export markdown files during ingestion

- app/src/batch_process.py
- app/src/chainlit.py
https://navalabs.atlassian.net/browse/DST-709
- Fixed type error where `batch_process` was incorrectly defined as async while using synchronous chainlit message operations
- Made `batch_process` synchronous and wrapped it with `cl.make_async` in the chainlit handler
- Maintains proper async/sync boundaries while keeping sequential processing for thread safety
The code had a type mismatch where `batch_process` was async but contained synchronous chainlit operations (`cl.Message.send()`). This caused mypy errors and potential issues with message delivery. The fix:
1. Makes `batch_process` synchronous since it contains synchronous operations
2. Uses `cl.make_async` in the chainlit handler to properly handle async/sync boundaries
3. Keeps the sequential processing to maintain thread safety …
> fix: Use cl.make_async when calling synchronous batch_process

- .github/workflows/README.md
- .github/workflows/markdownlint-config.json
- app/gunicorn.conf.py
- app/src/batch_process.py
- app/src/chat_engine.py
- docs/infra/set-up-database.md
- infra/app/app-config/dev.tf
https://navalabs.atlassian.net/browse/DST-709
- Increased ECS task memory from 8GB to 16GB in dev environment
- Reduced retrieval_k from 50 to 25 documents in ImagineLaEngine to optimize memory usage
- Added explicit Gunicorn timeout settings (300s) to prevent worker timeouts
We were seeing worker timeout errors in the logs during batch processing. This PR implements two optimizations:
1. Infrastructure: Doubled the available memory for the ECS task
2. Application: Reduced the number of documents retrieved per query and increased worker timeout limits
- Deployed ECS changes to dev environment:`./bin/terraform-init infra/app/service dev && make infra-update-app-service APP_NAME=app ENVIRONMENT=dev`
- Verified ECS task is running with new memory settings: `aws ecs describe-task-definition …
> fix: Refine memory handling and timeout params for batch processing

- app/Makefile
- app/pyproject.toml
- app/src/chat_engine.py
- app/src/ingest_edd_web.py
- app/src/ingest_irs_web.py
- app/src/ingest_la_county_policy.py
- app/src/ingestion/scrape_irs_web.py
- app/src/ingestion/scrapy_dst/cache.py
- app/src/ingestion/scrapy_dst/settings.py
- app/src/ingestion/scrapy_dst/spiders/irs_spider.py
- app/tests/src/test_chat_engine.py
- app/tests/src/test_ingest_irs_web.py
https://navalabs.atlassian.net/browse/DST-672
* Add IRS web scraper for https://www.irs.gov/credits-deductions/family-dependents-and-students-credits
* Add ingestion scripts to `Makefile` and `poetry`
* Add IRS dataset to chat engine
```
make scrape-irs-web
make ingest-irs-web DATASET_ID="IRS" BENEFIT_PROGRAM="tax credit" BENEFIT_REGION="US" FILEPATH=src/ingestion/irs_web_scrapings.json INGEST_ARGS=""
```
> feat: Add IRS family tax credit webpages as a new dataset

- app/src/app.py
Reference fix: https://github.com/navapbc/labs-decision-support-tool/pull/182/files#r1919131709
Tests showing locahost:3000 is blocked but localhost:5173 is valid:
```bash
labs-decision-support-tool/app on  DST-722-limit-cors-policy [?] ➜ curl -v -H "Origin: http://localhost:3000" -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: Content-Type" -X OPTIONS http://localhost:8000/api/query
* Host localhost:8000 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8000...
* Connected to localhost (::1) port 8000
> OPTIONS /api/query HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/8.7.1
> Accept: */*
> Origin: http://localhost:3000
> Access-Control-Request-Method: POST
> Access-Control-Request-Headers: Content-Type
> 
* Request completely sent off
< …
```
> fix: Limit origins to localhost:5173 and remove pattern from regex

- app/src/ingestion/markdown_chunking.py
- app/src/ingestion/scrapy_dst/spiders/ca_public_charge_spider.py
- app/tests/src/test_ingest_ca_public_charge.py
https://navalabs.atlassian.net/browse/DST-<TICKET_NUMBER_HERE>
> Use title of webpage instead of h4 labels found on public charge site
Request by design.
Note:
Reingest after merge
> fix: revise headers in public charge content

- app/Makefile
Add `app-shell` to Makefile that creates a transient container to quickly run commands against the code base without the overhead of creating a new container with each `make ...` command.
Create a `main-app-shell` container: `make app-shell`
and leave it open to run any `make ...` commands:
```
make lint
make test
...
exit  # Or Ctrl-D
```
> dev experience: Add app-shell target to Makefile

- app/Makefile
- app/src/ingestion/scrapy_dst/spiders/irs_spider.py
- app/src/ingestion/scrapy_runner.py
Follow-on to #186
* Remove specific `scrape-*` Makefile targets for each Srapy dataset
* Add general `scrapy-runner` Makefile target
* Generalize `scrapy_runner.py`
Impact:
* Reduces the number files we need to remember to update when adding a new dataset for ingestion
```
make scrapy-runner
make scrapy-runner args="ca_ftb --debug"
```
> refactor: Generalize scrapy-runner

- app/src/chat_engine.py
[Slack](https://nava.slack.com/archives/C06ETE82UHM/p1737672114646719?thread_ts=1737671120.579439&cid=C06ETE82UHM)
Remove unused ImagineLA chat engine settings from UI
In chatbot web UI, open the chatbot's settings to ensure those 2 settings don't appear.
> fix: Remove unused ImagineLA chat engine settings from UI

- app/src/chainlit.py
Associated with investigating https://navalabs.atlassian.net/browse/DST-733
Add MessageAttributes to Literal AI message metadata so that we can investigate why RAG isn't being performed for certain questions.
The response in LiteralAI should now show attributes:
> feat: Add MessageAttributes to Literal AI message metadata

- app/src/citations.py
- app/tests/src/test_citations.py
https://navalabs.atlassian.net/browse/DST-713
* When a paragraph is followed by a list, keep the paragraph (aka intro sentence) with the list when splitting chunks into subsections/citations.
Updated unit test
> feat: Keep intro sentence with subsequent list

- app/src/chat_api.py
https://navalabs.atlassian.net/browse/DST-756
Replace `API:/query` in LiteralAI with the user's question under the `Name` column.
POST a question with new lines:
```
curl -X POST 'http://0.0.0.0:8000/api/query' -H 'Content-Type: application/json' -d '{ "session_id": "1234", "new_session": true, "message": "\nunemployment insurance \nbenefit deadlines?"}'
```
Check in LiteralAI for the thread name that uses only the first non-empty line of the `message`:
> feat: Use query as the LiteralAI thread name

- app/src/chainlit.py
- app/src/chat_engine.py
- app/tests/src/test_batch_process.py
- app/tests/src/test_chat_api.py
- app/tests/src/test_chat_engine.py
Supports investigation and solutioning for https://navalabs.atlassian.net/browse/DST-733
To facilitate testing [these hypotheses](https://navalabs.atlassian.net/browse/DST-733?focusedCommentId=10477) and improving the system prompt:
1. add `benefit_program` as an attribute that the LLM should populate
2. explicitly show the message attributes in the UI so they can be quickly assessed (instead of having to wait for Literal AI to be updated and searching for the corresponding message).
Enable "Show message-assessment attributes" in the chatbot settings, submit a query, expect to see message attributes after the response:
> feat: Add benefit_program to ImagineLA_MessageAttributes

- app/src/chat_engine.py
- app/src/ingest_runner.py
- app/src/ingester.py
- app/src/ingestion/imagine_la/ingest.py
- app/src/util/ingest_utils.py
- app/tests/src/test_chat_engine.py
https://navalabs.atlassian.net/browse/DST-751
* Add ingester for SSA
* Add SSA dataset to chat engine
Download `ssa_scrapings.json` and `ssa_extra_md/` folder from https://us-east-1.console.aws.amazon.com/s3/buckets/decision-support-tool-app-dev?region=us-east-1&bucketType=general&prefix=ssa/
```
make ingest-runner args="ssa --json_input=ssa_scrapings.json"
```
Query chatbot:
Reminder to ingest into deployed app
```
> aws s3 cp ssa_scrapings.json s3://decision-support-tool-app-dev/ssa/ssa_scrapings.json
upload: ./ssa_scrapings.json to s3://decision-support-tool-app-dev/ssa/ssa_scrapings.json
> aws s3 sync ssa_extra_md s3://decision-support-tool-app-dev/ssa/ssa_extra_md
upload: ssa_extra_md/EN-05-10095/page05.md to s3://decision-support-tool-app-dev/ssa/ssa_extra_md/EN-05-10095/page05.md …
```
> feat: Ingest manual scraping of SSA pdf

- app/src/ingest_runner.py
- app/src/ingester.py
- app/tests/src/test_ingest_runner.py
- app/tests/src/test_ingester.py
Improvement for https://navalabs.atlassian.net/browse/DST-751
Allow ingesting from multiple JSON scraping files. This enables adding manually scraped JSON entries to automatically scrapped JSON.
```sh
> make ingest-runner args="ssa --json_input=ssa_scrapings.json --json_input=src/ingestion/irs_scrapings.json --skip_db"
2025-02-10 15:57:36,706 - INFO - Loaded 10 items from 'ssa_scrapings.json'
2025-02-10 15:57:36,708 - INFO - Loaded 31 items from 'src/ingestion/irs_scrapings.json'
2025-02-10 15:57:36,708 - INFO - Merged 2 files into 41 items in 'ssa_combined_scrapings.json'
2025-02-10 15:57:36,710 - INFO - Ingesting from 'ssa_combined_scrapings.json': {'dataset': 'SSA', 'program': 'social security', 'region': 'US'}
...
```
See that `ssa_md/ssa_combined_scrapings.json` is indeed a …
> feat: Ingest from multiple JSON scraping files

- app/Makefile
- app/src/chat_engine.py
- app/src/ingestion/imagine_la/ingest.py
- app/tests/src/ingestion/imagine-la/test_ingest.py
- app/tests/src/test_ingest_utils.py
https://navalabs.atlassian.net/browse/DST-768
Update Imagine LA's URL: `benefitnavigator.web.app`
(Imagine LA) SBN Content Hub
```
cd app
make scrape-imagine-la CONTENTHUB_PASSWORD=sbn
ls -al src/ingestion/imagine_la/scrape/pages
rm -rf imagine_la_md/
make ingest-imagine-la DATASET_ID="Imagine LA" BENEFIT_PROGRAM=mixed BENEFIT_REGION=California FILEPATH=src/ingestion/imagine_la/scrape/pages
...
2025-02-10 21:47:01,308 - INFO - Finished ingesting 'Imagine LA' (imagine_la)
```
Zip markdown files for archiving to Google Drive:
```
ls -al imagine_la_md
rm -f imagine_la_md.zip
zip imagine_la_md.zip -r imagine_la_md/
```
Query ask instructed in the ticket and check the URL:
> chore: Update Imagine LA's URL: benefitnavigator.web.app

- app/src/app.py
N/A
- Updated CORS `allow_origin_regex` pattern to match new dev environment URL format
- Before: `r"https://dev-social-benefits-navigator--nava-chatbot-.*\.web\.app"`
- After: `r"https://dev-social-benefits-navigator-.*\.web\.app"`
- Need to verify CORS allows requests from the updated dev URL pattern
> fix: new CORS allow_origin_regex pattern

- app/src/chat_api.py
[Slack](https://nava.slack.com/archives/C07U7LJ8GRX/p1739480852230819)
Add `source_dataset` field to the Citation API response so that API clients can display the dataset name for citations.
None
> feat: API: Add source_dataset field to the Citation API response

- app/refresh-ingestion.sh
- app/src/chat_engine.py
- app/src/ingestion/imagine_la/ingest.py
- app/src/metrics/evaluation/batch.py
- app/tests/src/ingestion/imagine-la/test_ingest.py
- app/tests/src/metrics/evaluation/test_batch.py
- app/tests/src/test_chat_engine.py
- app/tests/src/test_ingest_utils.py
https://navalabs.atlassian.net/browse/DST-769
Rename "Imagine LA" to "Benefits Information Hub"
Reingested for deployed app:
```
./bin/run-command app dev '["ingest-imagine-la", "Benefits Information Hub", "mixed", "California:LA County", "s3://decision-support-tool-app-dev/imagine_la-2025-02-10/"]'
```
```
make ingest-imagine-la DATASET_ID="Benefits Information Hub" BENEFIT_PROGRAM=mixed BENEFIT_REGION=California FILEPATH=src/ingestion/imagine_la/scrape/pages
```
> chore: Rename Imagine LA to Benefits Information Hub

- app/Makefile
- app/src/metrics/README.md
- app/src/metrics/cli.py
- app/tests/src/metrics/test_cli.py
N/A
- Fixed `--dataset` argument in `app/src/metrics/cli.py` to handle multiple datasets and k values using `nargs="+"` in the make command for `run-evaluation`:
- Also changed dataset filter parsing to split comma-separated values into a list
- This (still) allows running evals on multiple datasets and/or k simultaneously (e.g., `...dataset="imagine_la la_policy", k="5 10"...`)
When trying to evaluate multiple datasets, the command would fail because it was treating the comma-separated list as a single dataset name.
Fix modifies dataset arguments parsing, similar to how we handle k-values. We can pass multiple datasets using a comma-separated list.
Note: We currently only support 'imagine_la' and 'la_policy' datasets. This will be expanded to include other datasets (ca_wic, edd, etc.) as …
> fix: Support multiple datasets and k values using nargs in evaluation CLI

- app/src/ingestion/scrapy_dst/spiders/ca_public_charge_spider.py
https://navalabs.atlassian.net/browse/DST-743
* Use `response.urljoin()` to resolve `href` links in anchors, instead of prepending `response.url` to relative `href`s
* Clean up code
```
./refresh-ingestion.sh ca_public_charge
```
Check URLs in `app/src/ingestion/ca_public_charge_scrapings.json-pretty.json`
Follow instructions in ticket.
> fix: CA Public Charge dataset: fix absolute links

- app/src/chat_engine.py
- app/src/citations.py
- app/src/format.py
- app/tests/src/test_citations.py
- app/tests/src/test_format.py
https://navalabs.atlassian.net/browse/DST-731
* Add `move_citations_after_punctuation()` and unit test
* Updated Chatbot API, Batch Processing, and Chainlit UI to used new method
* Removed unused old method `reify_citations()`
See unit test
Paragraphs:
Bullets:
> feat: Move '(citation-N)' after punctuation

- infra/app/service/main.tf
https://navalabs.atlassian.net/browse/DST-671
- Subscribe group email address to existing CloudWatch alarms
- The latency threshold is probably too strict (200ms) for the API routes that call an LLM, but we can start here and tune upward as needed.
- After making this change I applied it with:
```
make infra-update-app-service APP_NAME=app ENVIRONMENT=dev
make infra-update-app-service APP_NAME=app ENVIRONMENT=prod
```
In retrospect I should have waited for PR approval!
You can see the alarms here:
https://github.com/navapbc/labs-decision-support-tool/blob/main/infra/modules/monitoring/main.tf#L12
N/A -- existing platform functionality
> feat: Subscribe monitoring email to CloudWatch alarms

- app/src/chat_api.py
- app/tests/src/test_chat_api.py
https://navalabs.atlassian.net/browse/DST-816
Don't wrap the `alert_msg` around the `**Policy update**` and `The rest of this answer may be outdated.` text twice.
`engine.on_message` already does this.
Unit test already exists but since it mocks `engine.on_message`, this bug wasn't apparent.
I fixed the mock to return the pre-wrapped text.
> fix: Remove repeated text around alert_msg

- app/src/chat_api.py
- app/tests/src/test_chat_api.py
https://navalabs.atlassian.net/browse/DST-815
Chat history for a single session is now correctly reflected in LiteralAI.
https://nava.slack.com/archives/C06DP498D1D/p1740507232929499
```
curl -X POST 'http://0.0.0.0:8000/api/query' -H 'Content-Type: application/json' -d '{ "session_id": "A123", "new_session": true, "message": "what do you know about?"}'
curl -X POST 'http://0.0.0.0:8000/api/query' -H 'Content-Type: application/json' -d '{ "session_id": "A123", "new_session": false, "message": "list programs"}'
curl -X POST 'http://0.0.0.0:8000/api/query' -H 'Content-Type: application/json' -d '{ "session_id": "A123", "new_session": false, "message": "Thanks"}'
```
Check in LiteralAI
> fix: Enable multiple user messages per LiteralAI thread

- app/src/chat_api.py
- app/tests/src/test_chat_api.py
n/a
- Temporarily allow empty user id strings in requests
- Unblock development team testing by temporarily allowing an empty user string while the issue is addressed on the frontend
> fix: Temporarily allow empty user id

- app/refresh-ingestion.sh
- app/src/ingestion/scrapy_dst/spiders/edd_spider.py
https://navalabs.atlassian.net/browse/DST-820
Update the EDD scraper to handle a particular webpage (https://edd.ca.gov/en/jobs_and_training/Layoff_Services_WARN/) so that the manual fix is not needed during ingestion.
```
./refresh-ingestion.sh edd
```
> fix: Remove manual fix for EDD datasource

- app/refresh-ingestion.sh
- app/src/ingestion/scrapy_dst/spiders/edd_spider.py
https://navalabs.atlassian.net/browse/DST-828
Add `echo_cmds()` to `refresh-ingestion.sh` to print out the commands to ingest into the deployed DB.
Once we're comfortable with automating those commands, update the script in another PR to execute those commands.
```
./refresh-ingestion.sh   # lists dataset ids
```
After each of the following, copy and paste the printed commands into a terminal to ensure they work. Verify in S3 bucket.
```
./refresh-ingestion.sh cmds imagine_la
./refresh-ingestion.sh cmds ca_ftb
./refresh-ingestion.sh cmds covered_ca
...
```
To update prod, run `export DEPLOY_ENV=prod` before the above commands.
> chore: Add echo_cmds() to refresh-ingestion.sh

- app/refresh-ingestion.sh
NA
- Changed region parameter from "California:LA County" to "California" to match ingest_imagine_la() expected params
- Updated `echo_cmds` function to accept `DATASET_ID` parameter
- Standardized region parameter to "California" for imagine_la dataset
- `echo_cmds` function wasn't properly handling imagine_la dataset paths. Added `DATASET_ID` parameter to generate correct S3 paths and ingestion commands.
- region parameter "California:LA County" in ingest_imagine_la() expects just "California"
- Ran ingestion script locally: `./refresh-ingestion.sh imagine_la`
- Ran S3 upload and ingestion on dev environment completed successfully
- Confirmed HTML files processed into chunks in database
```
> CONTENTHUB_PASSWORD=sbn ./refresh-ingestion.sh imagine_la
> aws s3 sync …
```
> fix: Imagine LA ingest: switch region to "California" and pass DATASET_ID to echo_cmds

- .gitignore
- app/.gitignore
- app/refresh-ingestion.sh
- app/src/ingest_runner.py
- app/src/util/ingest_utils.py
- app/tests/src/test_ingest_utils.py
https://navalabs.atlassian.net/browse/DST-809
- Added `all` argument to `refresh-ingestion.sh` to facilitate ingestion for all datasets for both dev and prod
- Added `--drop-only` ingest option to only drop the dataset so that ingestion can use `--resume` in subsequent runs
- Save AWS-related commands to separate script files to be executed separately since they affect the deployments and some commands can fail due to AWS resources.
```
./refresh-ingestion.sh all
```
then follow the instructions
```
- Review and run the refresh scripts (in the top-level folder): ...
- Restore local TF to dev environment: ./bin/terraform-init infra/app/service dev
```
> feat: Facilitate 'all' datasets in refresh-ingestion.sh

- app/src/app.py
n/a
- Update CORS regex for dev instances as well as the prod URL
n/a
From an Imagine LA dev environment, confirming the new regex still allows requests:
From an Imagine LA prod environment BEFORE this change:
From an Imagine LA prod environment AFTER the change:
> fix: Allow CORS from prod environment

- app/src/evaluation/cli/evaluate.py
- app/src/evaluation/cli/generate.py
- app/src/evaluation/data_models.py
- app/src/evaluation/qa_generation/generator.py
- app/src/evaluation/qa_generation/runner.py
- app/src/evaluation/utils/storage.py
- app/tests/src/evaluation/cli/test_cli_evaluate.py
- app/tests/src/evaluation/cli/test_cli_generate.py
- app/tests/src/evaluation/qa_generation/test_qa_generation_runner.py
- app/tests/src/evaluation/utils/test_storage.py
NA
- Added versioned storage system for QA pairs
- Timestamp-based versioning with metadata (e.g., `20250307_011423/`)
- Stores QA pairs in versioned directories with metadata.json
- Maintains "latest" symlink for easy access
- Version-specific metadata (LLM model, git commit, etc.)
- Updated tests to work with new storage
- cli tests to handle versioned QA pairs
- integration tests for the QA generation with versioning
Introduced feature versioned storage system for QA pairs to improve traceability + reproducibility
Passing with `make test`
`make generate-qa dataset="la_policy" sampling=0.005 && make evaluate k="5"`
> feat: Add versioned storage system for QA pairs with tests

- infra/modules/database/main.tf
n/a
- Prod DB resource usage is about ~50% at the current pilot -- bump the ceiling from 1.0 to 4.0 so there's room to scale in case needed.
Will run `make infra-update-app-database APP_NAME=app ENVIRONMENT=prod` once this is approved and merged
n/a
> chore: Bump DB max capacity

- app/src/evaluation/literalai_exporter.py
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1741804943062599)
For LiteralAI exporter, handle (old) threads without `citation.source_dataset`
```
make literalai-exporter args="2024-07-01 2025-03-12"
```
> fix: LiteralAI exporter: handle threads without citation.source_dataset

- app/Makefile
- app/pyproject.toml
- app/src/chainlit.py
- app/src/util/literalai_util.py
https://navalabs.atlassian.net/browse/DST-857
[Slack](https://nava.slack.com/archives/C06ETE82UHM/p1741801462799589?thread_ts=1741799299.480569&cid=C06ETE82UHM)
Add utility to auto-tag LiteralAI threads based on user_id
Download `literalai_user_tags.json` from the ['LiteralAI logs' Google Drive folder](https://drive.google.com/drive/folders/1Me71t3HnBWpNGdLF7IXsv-qPTL5ZaSz6).
Set `LITERAL_API_KEY` env var for the prod or dev env
```
make literalai-tagger args="--dry-run"
make literalai-tagger
```
LiteralAI UI shows tags:
> feat: Utility to auto-tag LiteralAI threads based on user_id

- app/src/chat_engine.py
https://navalabs.atlassian.net/browse/DST-865
Remove this line from referral links in system prompt 1:
`Tax prep: [https://www.freetaxprepla.org/help](https://www.freetaxprepla.org/help)`
Asking for 'tax prep' in chatbot should not return tax prep link.
> chore: Remove Tax prep referral link

- app/src/evaluation/literalai_exporter.py
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1742320270627999)
LiteralAI exporter is erroring due to our upgrade of chainlit, which now creates a different thread tree than it did before, i.e., it's now creating more parent steps than it didn't before.
Skip LiteralAI threads tagged with `chainlit`.
Set the prod `LITERAL_API_KEY` and run:
```
make literalai-exporter args="2025-01-16 2025-03-19"
```
- Service endpoint: https://p-271-app-dev-721484110.us-east-1.elb.amazonaws.com
- Deployed commit: bb9e71cbad09e9a0d0f06bbc03d3d30d228d738d
> fix: LiteralAI exporter: ignore chainlit message

- app/src/chat_api.py
- app/tests/src/test_chat_api.py
Part 1 for https://navalabs.atlassian.net/browse/DST-867
Instead of creating a new `db.PostgresDBClient()` instance for each new DB session, use the same `db_session` when responding to a request, without having to pass it as an argument through intermediate functions. So put a `db_session` instance in a `ContextVar` to be safe for threads and asyncio tasks.
Secondary purpose of PR is to understand how to use `ContextVar` since `chainlit.context` uses it. `chainlit.context` is needed for the next PR to use Chainlit's data layer in the `chat_api.py`.
No change in behavior. Test with `curl` or http://localhost:8000/docs
- Service endpoint: https://p-272-app-dev-334197002.us-east-1.elb.amazonaws.com
- Deployed commit: 9728fb04e6126a6f4642d9008fb196e9b7e3e6d1
> refactor: API: use ContextVar for db_session

- app/src/adapters/db/clients/postgres_client.py
- app/tests/src/adapters/db/clients/test_postgres_client.py
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1742914226216779)
- URL encode the database password
- The DB password token used for RDS includes `:` which if not URL-encoded causes parsing issues for asyncpg
- Added test coverage, also confirmed by running the code to connect to the RDS database locally
- Service endpoint: https://p-276-app-dev-1061947334.us-east-1.elb.amazonaws.com
- Deployed commit: 5b32f10f85979a85891a80539b5a8fbd9640a2dd
> fix: Correctly URL-encode special characters in the database password

- app/src/util/literalai_util.py
- infra/app/app-config/env-config/scheduled_jobs.tf
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1743080416620329)
Automate running `literalai-tagger`, which tags LiteralAI threads to distinguish testing from pilot users, every 3 hours during the day.
Tested `make literalai-tagger` for dev and prod `LITERAL_API_KEY` env vars.
- Service endpoint: https://p-281-app-dev-666907410.us-east-1.elb.amazonaws.com
- Deployed commit: b6869eb7157228377e9ded9258d0c5576189fdfc
> ci: Add cron: literalai_tagger

- app/src/batch_process.py
- app/src/chat_api.py
- app/src/chat_engine.py
- app/src/citations.py
- app/src/db/models/document.py
- app/src/format.py
- app/tests/src/test_batch_process.py
- app/tests/src/test_chainlit.py
- app/tests/src/test_chat_api.py
- app/tests/src/test_citations.py
- app/tests/src/test_format.py
Part of https://navalabs.atlassian.net/browse/DST-646
Sequential contiguous subsections that are cited together are merged into a single citation.
Also:
- fix bullet rendering by ensuring a new line occurs before any bullet character.
- fix extra spaces after citation heading
Citation #3 merges 3 citations/paragraphs:
- Service endpoint: https://p-282-app-dev-1134576066.us-east-1.elb.amazonaws.com
- Deployed commit: 8dda71b2fade3f0a5f220154301b22586c976d75
> feat: Merge contiguous cited subsections

- app/src/ingestion/scrapy_dst/spiders/la_policy_spider.py
https://navalabs.atlassian.net/browse/DST-898
Add `URLS_TO_SKIP` to `la_policy_spider.py`
```
make scrapy-runner args="la_policy --debug" &> scrapy.log
grep "Skipping URL" scrapy.log
```
Also check that no content from https://epolicy.dpss.lacounty.gov/epolicy/epolicy/server/general/projects_responsive/ePolicyMaster/mergedProjects/Medi-Cal/Medi-Cal/Coverage_for_Immigrants/Coverage_for_Immigrants.htm is present in `src/ingestion/la_policy_scrapings.json-pretty.json`
- Service endpoint: https://p-286-app-dev-2103794513.us-east-1.elb.amazonaws.com
- Deployed commit: e133955f0ae8e30fb0913a7f52ecd1c43e7a1610
> chore: Exclude out-of-date DPSS webpage Coverage_for_Immigrants

- app/src/ingestion/scrapy_dst/spiders/la_policy_spider.py
https://navalabs.atlassian.net/browse/DST-916
- Don't populate skipped URLs in the JSON as `{}`, omit them entirely
- Remove leading asterisks for both `* **_NOTE_**` and `* ** _NOTE_ **` (extra space in second one)
Looks like a minor formatting change on the LA policy website side
`./refresh-ingestion.sh la_policy` should run scraping, parsing, and ingestion successfully
- Service endpoint: https://p-290-app-dev-603792696.us-east-1.elb.amazonaws.com
- Deployed commit: 103ca48a79af50a26037515028471945ad362761
> fix: LA policy ingestion formatting change

- app/src/batch_process.py
- app/tests/src/test_batch_process.py
n/a
Instead of splitting on newlines, feed the file contents directly as an IOStream into CSVDictReader. This prevents newlines from being stripped from multi-line rows, e.g.,:
```
question,next_col
"This question
goes across multiple lines",1
```
Req from our eval partners at Georgetown
Updated unit tests to reflect, they should fail without the patch here
- Service endpoint: https://p-294-app-dev-236366550.us-east-1.elb.amazonaws.com
- Deployed commit: a68d5d2ce7fe6607e063d1c5649062aaa117fdc5
> fix: Preserve new lines in batch CSV processing

- app/src/chainlit.py
https://navalabs.atlassian.net/browse/DST-946
- Changed `on_message` in chainlit.py to use our new streaming functionality:
- `on_message_streaming()` to get async response generator
- Streams tokens in with `msg.stream_token()`
- `msg.update()` to get final message with remapped citations and formatting
Adds streaming support to our Chainlit UI interface
Works by:
1. Creating empty message first then streams tokens
2. After streaming is done, updates message with remapped and formatted citations
3. Reuses all existing functionality for the citations remapping, metadata, and tthe attributes
Chainlit docs:
- [Streaming Messages](https://docs.chainlit.io/api-reference/message#stream-a-message)
- [Updating Messages](https://docs.chainlit.io/api-reference/message#update-a-message)
Tested …
> feat: Add streaming to chainlit chat UI

- app/src/chat_api.py
- app/tests/src/test_chat_api.py
If `LITERAL_API_KEY_FOR_API` is set locally, a LiteralAI data layer is created unintentionally.
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1746027863743589?thread_ts=1746017995.398199&cid=C06DP498D1D)
Adding `monkeypatch.setattr(app_config, "literal_api_key_for_api", "")` in `mock_lai()` prevents the LiteralAI data layer from being created.
Reasoning:
- `mock_lai()` is called before `chainlit_data_layer()`, which is called by `@cl.data_layer`
- so monkeypatch in `mock_lai()`  before `app_config.literal_api_key_for_api` is accessed in `chainlit_data_layer()`
- Service endpoint: https://p-300-app-dev-277212110.us-east-1.elb.amazonaws.com
- Deployed commit: b626616bb0ed515f2082747ff5f74d948d2f3e81
> fix: Don't create LiteralAI data layer in test_chat_api

- app/src/chat_engine.py
https://navalabs.atlassian.net/browse/DST-951
- Updated `system_prompt_1` in ImagineLaEngine to improve referral link decision criteria
- Added specific decision criteria for when to use referral links
- Examples to illustrate correct usage
Message analysis prompt was incorrectly using referral links for questions about foster youth resources, where it should have instead searched the knowledge base. The previous prompt instruction was previously: "If the user's question is about a referral link below...". This appeared to lead to false positives where LLM serves an irrelevant link for foster youth resource questions.
Proposed edits makes criteria explicit and defaults to `need_context=True` when uncertain. [Slack link](https://nava.slack.com/archives/C06DP498D1D/p1746041077878979)
Tested …
> fix: Improve referral link decision criteria in ImagineLaEngine

- app/src/chat_engine.py
- app/src/generate.py
- app/tests/src/test_batch_process.py
- app/tests/src/test_chainlit.py
- app/tests/src/test_chat_api.py
- app/tests/src/test_chat_engine.py
- app/tests/src/test_format.py
https://navalabs.atlassian.net/browse/DST-956
Add 'translated to the same language as the user's question' to prompt
Ask questions that would trigger a canned response or alert message in a non-English language; expect response to be in the non-English language.
- Service endpoint: https://p-302-app-dev-1677135999.us-east-1.elb.amazonaws.com
- Deployed commit: f7ca917ec4c5604a773f1eeafba16838d8012404
> fix: Translate canned response and alert message to the same language as the user's question

- docs/app/evaluation/generateUniqueId.js
- docs/app/evaluation/promptfoo-config-template.yaml
- docs/app/evaluation/promptfoo-google-sheets.md
- docs/app/evaluation/promptfooconfig-template.yaml
https://navalabs.atlassian.net/browse/DST-937
- `docs/app/evaluation/generateUniqueId.js`: generate unique IDs for Promptfoo test sessions.
- `docs/app/evaluation/promptfoo-config-template.yaml`: template configuration for using Promptfoo.
- `docs/app/evaluation/promptfoo-google-sheets.md`: documentation to get started with Promptfoo and integrate with Google Sheets for chatbot evaluation.
PR outlines setup process with PromptFoo and Google Sheets, how to run evaluations from CLI, and write results back to Google Sheets
NA
- Service endpoint: https://p-306-app-dev-1957213931.us-east-1.elb.amazonaws.com
- Deployed commit: 1bbc195f5a2d6e544cddb604e087924e8cb82a8c
> docs: PromptFoo getting started with Google Sheets

- .gitignore
- app/refresh-ingestion.sh
- docs/data-management.md
https://navalabs.atlassian.net/browse/DST-906
* Run ingestion AWS tasks in the background
* Add `sleep 5` between invocations to avoid Terraform `Error locking state: [{%!s(tfdiags.Severity=69) Error acquiring the state lock Error message: resource temporarily unavailable`
* Add `poll_until_finished` function to check task status and wait for completion
* Updated md instructions
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1747093738438519?thread_ts=1747083614.517959&cid=C06DP498D1D)
- Service endpoint: https://p-309-app-dev-1487272209.us-east-1.elb.amazonaws.com
- Deployed commit: d301a585aa1b5fa9779b04c9002af5e66bcc91b5
> feat: Run refresh-ingestion in parallel

- .github/workflows/promptfoo-googlesheet-evaluation.yml
- app/promptfoo/promptfooconfig.ci.yaml
* Fixed promptfoo export functionality by properly handling evaluation IDs for the Google Sheets export
* Added nice-to-know checks validating the Google credentials and OpenAI API key
The main fix addresses the promptfoo export functionality by adding explicit export command to Google Sheets
Local testing using: 
`act pull_request -W .github/workflows/promptfoo-googlesheet-evaluation.yml --secret-file .secrets -e test-event.json --container-architecture linux/amd64 -v`
Testing for Github Actions on this branch
> fix: resolve Promptfoo exports to Google Sheet

- .github/workflows/promptfoo-googlesheet-evaluation.yml
- Fixed evaluation ID extraction in GH Action to capture eval ID from promptfoo output URL
Previously the workflow was trying to extract the eval ID from the JSON output file, but Promptfoo actually provides it in the CLI output URL. Changd script to capture and parse this URL instead.
- Tested by running the PR=true workflow - confirmed results are now being exported to the Google Sheet.
- Need to test it correctly exports results to Google Sheets when running manually via Actions UI (only available in main branch)
Attempted to use `act workflow_dispatch` for local testing of a non-pull request event but still getting errors and haven't had luck debugging
- Service endpoint: https://p-310-app-dev-652842717.us-east-1.elb.amazonaws.com
- Deployed commit: …
> ci: Extract evaluation ID from share URL

- app/src/ingestion/scrapy_dst/spiders/covered_ca_spider.py
[Slack](https://nava.slack.com/archives/C06DP498D1D/p1747763179422329)
The scraped markdown looks like:
```md
Copays are a fixed out-of-pocket amount paid for covered services. Insurance providers often charge copays for services such as doctor visits or prescription drugs. Your deductible is the amount you pay out of pocket for health care services covered under your insurance plan before your plan begins to pay for eligible expenses. The amount you pay for a health insurance deductible is determined by the type of plan you choose. Coinsurance is your share of costs for a covered health care service after the deductible is reached. It's calculated as a percentage.   
---
```
Note the `---` at the end, which denotes that the text above it is a heading! 
The cause is [this particular …
> fix: Ignore table formatting for CoveredCA data source

- .github/workflows/promptfoo-googlesheet-evaluation.yml
- app/promptfoo/promptfooconfig.ci.yaml
- app/promptfoo/readability_assessment.py
https://navalabs.atlassian.net/browse/DST-936
- Added TextDescriptives and spacy as dependencies to our GitHub Actions workflow
- Added readability_assessment.py to workflow trigger paths
- Configured workflow to copy readability assessment script to temp directory
Get necessary dependencies and file setup for running readability assessments in the promptfoo evaluation workflow. The readability assessment script uses textdescriptives and spacy to analyze chatbot responses when we use the "readability" rubric value. It uses metrics like Flesch-Kincaid grade level and Flesch reading ease scores.
_Sidenote:_
> I opted for textdescriptives over py-readability because there was a version incompatibility blocking the NLTK 'punkt' vocabulary download likely due to poor repository maintenance. …
> ci: Add readability assessment to promptfoo GHA workflow

- app/src/evaluation/data_models.py
- app/src/evaluation/metrics/metric_computation.py
- app/src/evaluation/metrics/results.py
- app/tests/src/evaluation/metrics/test_logging.py
- app/tests/src/evaluation/metrics/test_metric_computation.py
- app/tests/src/evaluation/metrics/test_metric_models.py
- app/tests/src/evaluation/metrics/test_results.py
https://navalabs.atlassian.net/browse/DST-970
- Added `document_id` field to `ExpectedChunk` and `RetrievedChunk` data models
- `correct_document_retrieved` and `document_rank_if_found` fields in `EvaluationResult`
- `document_recall_at_k` field in `DatasetMetrics`
- Updatd `process_retrieved_chunks()` to calculate document-level recall
- `compute_dataset_metrics()` and `compute_metrics_summary()` now include document recall metrics
- Updated tests to include th new required fields
Document-level recall measures if the correct document (not only the correct chunk) appears in the retrieved results. The idea is this provides us a better baseline for comparing embedding models that produce different chunk sizes.
To do this we compare `document_id` of expected chunk against `document_id` of …
> feat: Add document-level recall to retrieval evaluation pipeline

- .github/workflows/promptfoo-googlesheet-evaluation.yml
- docs/promptfoo-evaluations.md
Related to https://navalabs.atlassian.net/browse/DST-985
Correct instructions: remove SSL from the `Chatbot API endpoint URL` for preview environments.
Also add more logging to GH Action.
URLs are [shown](https://github.com/navapbc/labs-decision-support-tool/actions/runs/15427823055/job/43419024962?pr=316#step:9:19) for traceability
- Service endpoint: https://p-316-app-dev-2032634175.us-east-1.elb.amazonaws.com
- Deployed commit: 0790e5874e3c341ab0bcd5937b9aca844159e499
> doc: Promptfoo evaluations instructions: don't use SSL
